### PR TITLE
add support for captions

### PR DESCRIPTION
**Pull request by micnem**

### CODE REVIEW

**Comment by micnem** [comment]
https://user-images.githubusercontent.com/29963598/230628813-be16e372-df38-450a-8f40-44d00a4f475f.mp4

**Comment by micnem** [comment]
https://user-images.githubusercontent.com/29963598/230629672-d92c5d8e-2c23-4f25-9ae9-2b05dbbf2b6c.mp4

**Review by dewinterjack — APPROVED** [review]
LGTM

**Comment by micnem** [comment]
> LGTM

what does this meeeeean

**Pull request merged**
